dist: xenial
language: python
python: 
  - "3.9.1"
services:
  - postgresql
env:
  - DJANGO=3.1.4 DB=postgres
global:
  - PGPORT=5432
before_install:
  - sudo service postgresql stop
  - sudo apt install -yq --no-install-suggests --no-install-recommends postgresql-13-postgis-3-scripts postgresql-13 postgresql-client-13 postgresql-13-postgis-3
  - sed -e 's/^port.*/port = 5432/' /etc/postgresql/13/main/postgresql.conf > postgresql.conf
  - sudo chown postgres postgresql.conf
  - sudo mv postgresql.conf /etc/postgresql/13/main
  - sudo cp /etc/postgresql/{10,13}/main/pg_hba.conf
  - sudo service postgresql restart 13
  - sudo apt-get install -y gettext
install:
  - pip install -r requirements.txt
env:
  - DATABASE_URL=postgres://pwmcmwvalxobcz:8e51eaca927828431420d9db6450e427e02c23e32f4df26b572351191d5c4c11@ec2-18-203-62-227.eu-west-1.compute.amazonaws.com:5432/dcbrkjnp1ol12u
before_script:
  - cp ./Corrige/settings.py ./Corrige/local_settings.py
  - export PATH="/usr/lib/postgresql/13/bin:$PATH"
  - sudo -u postgres createuser Kelsier
  - sudo -u postgres createdb corrige -O Kelsier
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py runscript populate
  - python manage.py compilemessages
script:
  - travis_wait 20 python manage.py test
addons:
  postgresql: "13"
  apt:
    packages:
      - postgresql-13
      - postgresql-client-13
branches:
  only:
    - release/s2/Despliegue-0.3
deploy:
  provider: heroku
  api_key: 9a4d80da-d656-4680-b72d-15e614a8245b
  app: verumapp
  on: release/s2/Despliegue-0.3